server:
  port: 8972

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver 
    url: jdbc:mariadb://localhost:6033/encore
    username: todo_user
    password: todo_passwd  

mybatis:
  mapper-locations: classpath:mappers/*.xml  # classpath 추가
